name: Adam Reilly
favicon: null
layout_spectrum: 0.57916
typography_spectrum: 0.77168
title: 'Adam Reilly, Civil 3D User'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b3b3b'
    - '#23594b'
    - '#53a94d'
    - '#3b7767'
  brandStrength: 0.182789248181507
  lightness: 0.8350940346717834
  saturation: 0.5969090985599905
  rhythmicContrast: 0.49125079181976616
purpose: []
